version: '3.8'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1402"
      POSTGRES_DB: ChewaDB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - my-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - my-network

volumes:
  postgres-data:

networks:
  my-network:
    driver: bridge